config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  resources :deals do
    collection do
      get :publish
    end
  end

  resources :sessions

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy' 

  resources :orders
  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deal.rb
class Deal < ApplicationRecord
  has_many :orders

  has_attached_file :image,
  Shoppers::Configuration.paperclip_options[:deals][:image]
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def publishable?
    title.present? && 
      description.present? && 
        price.present? && 
          discounted_price.present? && 
            quantity.present? && 
              image.present?
  end

  def quantity_left?
    quantity > 0
  end

  def already_purchased?(uid)
    orders.where(user_id: uid).present?
  end

  def valid_to_purchase?(uid)
    quantity_left? && !already_purchased?(uid)
  end

  def calculate_discount(uid)
    user_purchase_count = Order.where(user_id: uid).length
    discount_applied = user_purchase_count > 5 ? discounted_price * 0.05 : discounted_price * ((user_purchase_count)/100.0)
    selling_price = discounted_price - discount_applied 
  end

  def self.publish
    Deal.where(is_published: [nil, false]).each do |unpublished_deal|
      if unpublished_deal.publishable?
        unpublished_deal.update_attributes(is_published: true, publish_date: Time.now)
        break
      end
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :deal
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  

  def authenticate(password)
    self.password == password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  before_action :is_admin?, only: [:index, :new, :create]
  def index
    if is_admin?
      @deals = Deal.all 
    else
      flash.now[:error] = "Customer cannot access it"
      redirect_to login_path
    end
  end

  def new 
    @deal = Deal.new if is_admin?
  end

  def create
    if is_admin?
      @deal = Deal.new(deal_params)
      @deal.save
      @deals = Deal.all
      render 'index'
    end
  end

  def publish
    @deal_to_publish = Deal.where(is_published: true).order("publish_date").last
    @purchasable = @deal_to_publish.valid_to_purchase?(1)
  end

  private 

  def deal_params
    params.require(:deal).permit(:title, :description, :price, :discounted_price, :quantity, :image)
  end

  def is_admin?
    User.find_by_id(session[:user_id]).role == 'admin'
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :set_latest_deal, only: [:new, :create]
  def index
  end

  def new
    @discount_price = @latest_deal.calculate_discount(1)
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = 1
    @order.deal_id = @latest_deal.id
    @order.save
    @latest_deal.decrement!("quantity")
  end

  private

  def order_params
    params.require(:order).permit(:shipping_address, :actual_price)
  end

  def set_latest_deal
    @latest_deal = Deal.where(is_published: true).order("publish_date").last
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
   @session = Session.new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      if @user.role == 'admin'
        redirect_to deals_path
      else
        redirect_to publish_deals_path
      end
    else
      flash.now[:error] = "Incorrect Username/Password"
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/deals/index.html.erb
<%- model_class = Deal -%>
<div class ="container">
  <h1>All <%= model_class.model_name.human.pluralize.titleize %> </h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:title)%></th>
        <th><%= model_class.human_attribute_name(:description)%></th>
        <th><%= model_class.human_attribute_name(:quantity)%></th>
        <th><%= model_class.human_attribute_name(:publish_date)%></th>
      </tr>
    </thead>
    <tbody>
      <% @deals.each do |deal| %>
        <tr>
          <td><%= deal.id %></td>
          <td><%= deal.title %></td>
          <td><%= deal.description %></td>
          <td><%= deal.quantity %></td>
          <td><%= deal.publish_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="form-group">
      <div class="col-lg-12 bottom-margin">
        <%= link_to "+ Deal", new_deal_path, :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/deals/new.html.erb
<h1 class ="left-margin145"> Create a deal </h1>
<%= form_for @deal, :html => { :class => "form-horizontal" } do |f| %>
  <div class = "container" >
    <div class = "row">
      <div class = "col-lg-2">
        <%= f.label :title, :class => 'control-label' %>
      </div>
      <div class = "col-lg-3 bottom-margin">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>
    </div>
    <div class = "row">
      <div class = "col-lg-2">
        <%= f.label :description, :class => 'control-label' %>
      </div>
      <div class = "col-lg-3 bottom-margin">
        <%= f.text_field :description, :class => 'form-control' %>
      </div>
    </div>
    <div class = "row">
      <div class = "col-lg-2">
        <%= f.label :price, :class => 'control-label' %>
      </div>
      <div class = "col-lg-3 bottom-margin">
        <%= f.text_field :price, :class => 'form-control' %>
      </div>
    </div>
    <div class = "row">
      <div class = "col-lg-2">
        <%= f.label :discounted_price, :class => 'control-label' %>
      </div>
      <div class = "col-lg-3 bottom-margin">
        <%= f.text_field :discounted_price, :class => 'form-control' %>
      </div>
    </div>
    <div class = "row">
      <div class = "col-lg-2">
        <%= f.label :quantity, :class => 'control-label' %>
      </div>
      <div class = "col-lg-3 bottom-margin">
        <%= f.text_field :quantity, :class => 'form-control' %>
      </div>
    </div>
    <div class = "row">
      <div class = "col-lg-2">
        <%= f.label :image, :class => 'control-label' %>
      </div>
      <div class = "col-lg-3 bottom-margin">
        <%= f.file_field :image, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= link_to t('.create_deal', :default => t("helpers.links.create_deal")),
                deals_path, :class => 'btn btn-primary' %>

        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                deals_path, :class => 'btn btn-default' %>
      </div>
    </div>
  </div>
<% end %>

app/views/deals/publish.html.erb
<h2><center>Deal of the Day</center></h2>
<div class = "row">
  <h3><center><%= @deal_to_publish.title  %></center></h3>
</div>
<div class ="row">
  <h5><center><%= @deal_to_publish.description %></center></h5>
</div>
<div class="form-group">
  <div class="row">
    <% if @purchasable %>
      <center><%= link_to t('.buy_now'),
              new_order_path, :class => 'btn btn-default green-buy-button' %></center>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<ul class="nav navbar-nav menues">
  <% if session[:user_id].present? %> 
     <li class="menu-item pull-right"><%= link_to "Log Out", logout_path, :method => :delete %></li> 
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoppers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h3> Deal has been successfully purchased </h3>

app/views/orders/new.html.erb
<%= form_for @order, :html => { :class => 'form-horizontal' } do |f| %>

<h1 class ="left-margin145"> Purchase deal of the day </h1>
<div class="row left-margin145">
  <div class = "col-lg-2">
    <%= f.label 'Title', :class => 'control-label' %>
  </div>
  <div class = "col-lg-3 bottom-margin">
    <%= f.text_field :title, :value => @latest_deal.title, :disabled => true, :class => 'form-control' %>
  </div>
</div>
<div class="row left-margin145">
  <div class = "col-lg-2">
    <%= f.label 'Description', :class => 'control-label' %>
  </div>
  <div class = "col-lg-3 bottom-margin">
    <%= f.text_field :description, :value => @latest_deal.description, :disabled => true, :class => 'form-control' %>
  </div>
</div>
<div class="row left-margin145">
  <div class = "col-lg-2">
    <%= f.label 'Price', :class => 'control-label' %>
  </div>
  <div class = "col-lg-3 bottom-margin">
    <%= f.text_field :discount, :value => @latest_deal.discounted_price, :disabled => true, :class => 'form-control' %>
  </div>
</div>
<div class="row left-margin145">
  <div class = "col-lg-2">
    <%= f.label 'After discount price', :class => 'control-label' %>
  </div>
  <div class = "col-lg-3 bottom-margin">
    <%= f.text_field :actual_price, :value => @discount_price, :disabled => true, :class => 'form-control' %>
  </div>
</div>
<div class="row left-margin145">
  <div class = "col-lg-2">
    <%= f.label 'Enter shipping address', :class => 'control-label' %>
  </div>
  <div class = "col-lg-3 bottom-margin">
    <%= f.text_field :shipping_address, :class => 'form-control' %>
  </div>
</div>
<div class="form-group">
  <div class="col-lg-offset-3 col-lg-10">
   <%= link_to t('.Confirm'),
            orders_path, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            deals_path, :class => 'btn btn-default' %>
  </div>
</div>
<% end %>